export default {
    body: document.querySelector('body'),
    btnMenu: document.querySelector('.btn-menu'),
    iconBurger: document.querySelector('.btn-menu__icon-burger'),
    iconCross: document.querySelector('.btn-menu__icon-cross'),
    backdrop: document.querySelector('.backdrop'),
    modal: document.querySelector('.modal'),
    listModal: document.querySelector('.list-modal'),
    btnCallback: document.querySelector('.js-open-callback'),
    btnCloseCallback: document.querySelector('.modal-callback__btn-close'),
    backdropCallback: document.querySelector('.backdrop-callback'),
    modalCallback: document.querySelector('.modal-callback'),
    timerNum: document.querySelector('.timer-num'),
    modalCallbackForm: document.querySelector('.modal-callback__form'),
    modalCallbackInput: document.querySelector('.modal-callback__input'),
    listService: document.querySelector('.list-service'),
}