import '../node_modules/swiper/swiper-bundle.min.css';
import './sass/main.scss';
import './js/common/common';
import './js/refs/refs';
import './js/menu';
import './js/swiper-hero';
import './js/callback-modal';
import './js/list-service-link';
import './js/list-link';
